name: Check issue Events
on: issues
jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Event
        run: |
          echo "searching"
          echo "${{github.event_name}}"
          echo "completed"

